version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: commerce_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: commerce_intelligence
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - commerce_pg_data:/var/lib/postgresql/data

volumes:
  commerce_pg_data: